### ISSUE TITLE
Double Vary header

### ISSUE THREAD

**Issue by redburn** [bacek/sdch_module#6]
Both the SDCH module and the gzip module set a Vary header, so you end up with this:

**Vary: Accept-Encoding** << set by gzip_vary
**Vary: Accept-Encoding, Avail-Dictionary** << set by sdch_vary

Basically, the header set by sdch_vary makes the one set by gzip_vary superfluous.

Is it possible for sdch_module to combine the two Vary headers, or to strip the one set by gzip_vary when the client advertises support for SDCH and the response is encoded with SDCH?

**Comment by bacek** [comment]
1. You can just switch off gzip_vary in nginx config. 
2. Duplicated Vary headers are handled properly in Chromium anyway.

**Comment by redburn** [comment]
I tried disabling gzip_vary like so, but it's not allowed to be used in an if block:

```
if ($http_accept_encoding ~* sdch) {
        gzip_vary       off;
}
```

Unfortunately, if I disable gzip_vary for all user agents, the Vary header will only be sent to those that announce support for SDCH. It's not a big issue; just the fewer headers, the merrier.

**Comment by redburn** [comment]
Ended up disabling gzip_vary and sdch_vary, and setting the Vary header with add_header instead.

```
gzip_vary               off;
sdch_vary               off;
add_header              Vary 'Accept-Encoding, Avail-Dictionary';
```

**Comment by bacek** [comment]
Actually I'm going to fix it properly.

**Comment by bacek** [comment]
Oook. I can't fix it "properly".

For the record: `sdch_module` runs before `gzip_module` and we can't check that gzip_vary will be set. Because it depends on various factors: size of content, gzip_vary enabled in config, etc, etc. And `ngx_http_filter_module` sets `Vary: Accept-Encoding` without checking existence of previous header. 

So, best solution is ignore duplicated headers as per HTTP standard (HTTP/1.1 or HTTP/2) and it is what Chromium do.

**Comment by redburn** [comment]
Thanks for trying :) I'll stick to my current "solution".
